version: '3.8'

services:
  app:
    container_name: apps-ptia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor  # Persistent vendor directory
      - storage_data:/var/www/html/storage  # Persistent storage
      - ./public:/var/www/html/public  # Mount public directory
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    container_name: db-ptia
    image: mysql:8
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin9090!
      MYSQL_DATABASE: db_ptia
      MYSQL_USER: db_ptia
      MYSQL_PASSWORD: db_ptia
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d  # For initial SQL scripts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pAdmin9090!"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  phpmyadmin:
    container_name: pma-ptia
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-ptia
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Admin9090!
      UPLOAD_LIMIT: 128M
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:
  vendor_data:
  storage_data:

networks:
  app-network:
    driver: bridge
